---

- hosts: all
  become: true
  tasks:
    - name: update Repository index
      apt:
        update_cache: yes

    - name: Install curl package
      apt:
        name: curl
        state: latest

    - name: Add php support for Apache
      apt:
        name: libapache2-mod-php
        state: latest
