---

- hosts: all
  become: true
  tasks:
    - name: update Repository index
      apt:
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: Install tree package
      apt:
        name: tree
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: Add php support for Apache
      apt:
        name: libapache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu"
